
#ifndef id_h
#define id_h

#define id__Undefined_Tok 1
#define id__Unknown_Tok 2
#define id__Eol_Tok 3
#define id__Eof_Real 4
#define id__Eof_RParen 5
#define id__Eof_Backtick 6
#define id__Ignored_LineCont 7
#define id__Ignored_Space 8
#define id__Ignored_Comment 9
#define id__WS_Space 10
#define id__Lit_Chars 11
#define id__Lit_VarLike 12
#define id__Lit_Other 13
#define id__Lit_EscapedChar 14
#define id__Lit_LBrace 15
#define id__Lit_RBrace 16
#define id__Lit_Comma 17
#define id__Lit_DRightBracket 18
#define id__Lit_Tilde 19
#define id__Lit_Pound 20
#define id__Lit_Slash 21
#define id__Lit_Percent 22
#define id__Lit_Digits 23
#define id__Lit_At 24
#define id__Lit_ArithVarLike 25
#define id__Op_Newline 26
#define id__Op_Amp 27
#define id__Op_Pipe 28
#define id__Op_PipeAmp 29
#define id__Op_DAmp 30
#define id__Op_DPipe 31
#define id__Op_Semi 32
#define id__Op_DSemi 33
#define id__Op_LParen 34
#define id__Op_RParen 35
#define id__Op_DLeftParen 36
#define id__Op_DRightParen 37
#define id__Redir_Less 38
#define id__Redir_Great 39
#define id__Redir_DLess 40
#define id__Redir_TLess 41
#define id__Redir_DGreat 42
#define id__Redir_GreatAnd 43
#define id__Redir_LessAnd 44
#define id__Redir_DLessDash 45
#define id__Redir_LessGreat 46
#define id__Redir_Clobber 47
#define id__Redir_AndGreat 48
#define id__Redir_AndDGreat 49
#define id__Left_DoubleQuote 50
#define id__Left_SingleQuote 51
#define id__Left_Backtick 52
#define id__Left_CommandSub 53
#define id__Left_VarSub 54
#define id__Left_ArithSub 55
#define id__Left_ArithSub2 56
#define id__Left_DollarDoubleQuote 57
#define id__Left_DollarSingleQuote 58
#define id__Left_ProcSubIn 59
#define id__Left_ProcSubOut 60
#define id__Right_DoubleQuote 61
#define id__Right_SingleQuote 62
#define id__Right_Backtick 63
#define id__Right_CommandSub 64
#define id__Right_VarSub 65
#define id__Right_ArithSub 66
#define id__Right_DollarDoubleQuote 67
#define id__Right_DollarSingleQuote 68
#define id__Right_Subshell 69
#define id__Right_FuncDef 70
#define id__Right_CasePat 71
#define id__Right_ArrayLiteral 72
#define id__Right_ExtGlob 73
#define id__ExtGlob_At 74
#define id__ExtGlob_Star 75
#define id__ExtGlob_Plus 76
#define id__ExtGlob_QMark 77
#define id__ExtGlob_Bang 78
#define id__VSub_Name 79
#define id__VSub_Number 80
#define id__VSub_Bang 81
#define id__VSub_At 82
#define id__VSub_Pound 83
#define id__VSub_Dollar 84
#define id__VSub_Star 85
#define id__VSub_Hyphen 86
#define id__VSub_QMark 87
#define id__VTest_ColonHyphen 88
#define id__VTest_Hyphen 89
#define id__VTest_ColonEquals 90
#define id__VTest_Equals 91
#define id__VTest_ColonQMark 92
#define id__VTest_QMark 93
#define id__VTest_ColonPlus 94
#define id__VTest_Plus 95
#define id__VOp1_Percent 96
#define id__VOp1_DPercent 97
#define id__VOp1_Pound 98
#define id__VOp1_DPound 99
#define id__VOp1_Caret 100
#define id__VOp1_DCaret 101
#define id__VOp1_Comma 102
#define id__VOp1_DComma 103
#define id__VOp2_Slash 104
#define id__VOp2_Colon 105
#define id__VOp2_LBracket 106
#define id__VOp2_RBracket 107
#define id__Arith_Semi 108
#define id__Arith_Comma 109
#define id__Arith_Plus 110
#define id__Arith_Minus 111
#define id__Arith_Star 112
#define id__Arith_Slash 113
#define id__Arith_Percent 114
#define id__Arith_DPlus 115
#define id__Arith_DMinus 116
#define id__Arith_DStar 117
#define id__Arith_LParen 118
#define id__Arith_RParen 119
#define id__Arith_LBracket 120
#define id__Arith_RBracket 121
#define id__Arith_RBrace 122
#define id__Arith_QMark 123
#define id__Arith_Colon 124
#define id__Arith_LessEqual 125
#define id__Arith_Less 126
#define id__Arith_GreatEqual 127
#define id__Arith_Great 128
#define id__Arith_DEqual 129
#define id__Arith_NEqual 130
#define id__Arith_DAmp 131
#define id__Arith_DPipe 132
#define id__Arith_Bang 133
#define id__Arith_DGreat 134
#define id__Arith_DLess 135
#define id__Arith_Amp 136
#define id__Arith_Pipe 137
#define id__Arith_Caret 138
#define id__Arith_Tilde 139
#define id__Arith_Equal 140
#define id__Arith_PlusEqual 141
#define id__Arith_MinusEqual 142
#define id__Arith_StarEqual 143
#define id__Arith_SlashEqual 144
#define id__Arith_PercentEqual 145
#define id__Arith_DGreatEqual 146
#define id__Arith_DLessEqual 147
#define id__Arith_AmpEqual 148
#define id__Arith_PipeEqual 149
#define id__Arith_CaretEqual 150
#define id__Node_PostDPlus 151
#define id__Node_PostDMinus 152
#define id__Node_UnaryPlus 153
#define id__Node_UnaryMinus 154
#define id__Node_ArithVar 155
#define id__Node_Command 156
#define id__Node_Assign 157
#define id__Node_AndOr 158
#define id__Node_Block 159
#define id__Node_Subshell 160
#define id__Node_Fork 161
#define id__Node_FuncDef 162
#define id__Node_ForEach 163
#define id__Node_ForExpr 164
#define id__Node_NoOp 165
#define id__Node_UnaryExpr 166
#define id__Node_BinaryExpr 167
#define id__Node_TernaryExpr 168
#define id__Node_FuncCall 169
#define id__Node_ConstInt 170
#define id__Word_Compound 171
#define id__KW_DLeftBracket 172
#define id__KW_Bang 173
#define id__KW_For 174
#define id__KW_While 175
#define id__KW_Until 176
#define id__KW_Do 177
#define id__KW_Done 178
#define id__KW_In 179
#define id__KW_Case 180
#define id__KW_Esac 181
#define id__KW_If 182
#define id__KW_Fi 183
#define id__KW_Then 184
#define id__KW_Else 185
#define id__KW_Elif 186
#define id__KW_Function 187
#define id__KW_Time 188
#define id__Assign_Declare 189
#define id__Assign_Typeset 190
#define id__Assign_Local 191
#define id__Assign_Readonly 192
#define id__Assign_None 193
#define id__ControlFlow_Break 194
#define id__ControlFlow_Continue 195
#define id__ControlFlow_Return 196
#define id__ControlFlow_Exit 197
#define id__Char_OneChar 198
#define id__Char_Stop 199
#define id__Char_Hex 200
#define id__Char_Octal3 201
#define id__Char_Octal4 202
#define id__Char_Unicode4 203
#define id__Char_Unicode8 204
#define id__Char_Literals 205
#define id__Char_BadBackslash 206
#define id__Glob_LBracket 207
#define id__Glob_RBracket 208
#define id__Glob_Star 209
#define id__Glob_QMark 210
#define id__Glob_Bang 211
#define id__Glob_Caret 212
#define id__Glob_EscapedChar 213
#define id__Glob_BadBackslash 214
#define id__Glob_CleanLiterals 215
#define id__Glob_OtherLiteral 216
#define id__Glob_Eof 217
#define id__BoolUnary_o 218
#define id__BoolUnary_t 219
#define id__BoolUnary_v 220
#define id__BoolUnary_R 221
#define id__BoolUnary_a 222
#define id__BoolUnary_b 223
#define id__BoolUnary_c 224
#define id__BoolUnary_d 225
#define id__BoolUnary_e 226
#define id__BoolUnary_f 227
#define id__BoolUnary_g 228
#define id__BoolUnary_h 229
#define id__BoolUnary_L 230
#define id__BoolUnary_p 231
#define id__BoolUnary_r 232
#define id__BoolUnary_s 233
#define id__BoolUnary_S 234
#define id__BoolUnary_u 235
#define id__BoolUnary_w 236
#define id__BoolUnary_x 237
#define id__BoolUnary_O 238
#define id__BoolUnary_G 239
#define id__BoolUnary_N 240
#define id__BoolUnary_z 241
#define id__BoolUnary_n 242
#define id__BoolBinary_eq 243
#define id__BoolBinary_ne 244
#define id__BoolBinary_gt 245
#define id__BoolBinary_ge 246
#define id__BoolBinary_lt 247
#define id__BoolBinary_le 248
#define id__BoolBinary_ef 249
#define id__BoolBinary_nt 250
#define id__BoolBinary_ot 251
#define id__BoolBinary_GlobEqual 252
#define id__BoolBinary_GlobDEqual 253
#define id__BoolBinary_GlobNEqual 254
#define id__BoolBinary_EqualTilde 255
#define id__BoolBinary_Equal 256
#define id__BoolBinary_DEqual 257
#define id__BoolBinary_NEqual 258

#endif /* id_h */
